kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coastie-operator
subjects:
- kind: ServiceAccount
  name: coastie-operator
  namespace: coastie
roleRef:
  kind: ClusterRole
  name: coastie-operator
  apiGroup: rbac.authorization.k8s.io
