apiVersion: apps/v1
kind: Deployment
metadata:
  name: coastie-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: coastie-operator
  template:
    metadata:
      labels:
        name: coastie-operator
    spec:
      serviceAccountName: coastie-operator
      containers:
        - name: coastie-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - coastie-operator
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "coastie-operator"
            - name: WATCH_NAMESPACE
              value: ""

